#!/bin/bash

PARAM=x$1

if [ $PARAM = "xrelease" ]; then
    swift build -c release
else
    swift build -Xswiftc -DDEBUG

#	-Xswiftc -emit-library -Xswiftc -o -Xswiftc .build/debug/libSwiftLevelDB.so
fi
