#!/bin/bash

PARAM=x$1

if [ PARAM = "xrelease" ]; then
    swift build -c release
else
#    swift build -Xswiftc -DDEBUG
    swift build -v -Xswiftc -target -Xswiftc armv7-none-linux-androideabi -Xswiftc -DDEBUG -Xswiftc -emit-library -Xswiftc -o -Xswiftc .build/debug/libSwiftLevelDB.so
fi
